In [3]:
import pandas as pd

In [4]:
customers = pd.read_csv("../../data/raw/customers.csv")

customers.head()

   customer_id name gender  age city signup_date
0            1  김수민      F   19   광주  2024-08-14
1            2  김정호      F   32   대구  2025-12-28
2            3  이경수      F   61   성남  2024-08-07
3            4  조영호      F   55   울산  2026-06-08
4            5  이예원      F   19   부산  2024-11-08

In [5]:
customers.shape

customers.columns

Index(['customer_id', 'name', 'gender', 'age', 'city', 'signup_date'], dtype='str')

In [6]:
orders = pd.read_csv("../../data/raw/orders.csv")

In [7]:
orders.head()

   order_id  customer_id  order_date payment_method order_status
0         1          123  2026-07-02           card    completed
1         2           77  2025-09-17      naver_pay    cancelled
2         3          138  2026-01-14  bank_transfer    cancelled
3         4           57  2026-03-27      kakao_pay    cancelled
4         5          125  2026-02-15           card    cancelled

In [9]:
orders["order_status"] == "completed"

0       True
1      False
2      False
3      False
4      False
       ...
295     True
296     True
297    False
298     True
299    False
Name: order_status, Length: 300, dtype: bool

In [10]:
orders["order_status"].value_counts()

order_status
completed    184
cancelled     64
refunded      52
Name: count, dtype: int64

In [11]:
orders_completed = orders[orders["order_status"] == "completed"].copy()

In [12]:
orders_completed.shape

(184, 5)

In [13]:
customers["customer_id"].duplicated().sum()

np.int64(0)